# Generated by Django 6.0 on 2025-12-18 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=200, verbose_name='Produto/Serviço')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Observações da Arte')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Arte'), ('ARTE_PRODUCAO', 'Arte em Produção'), ('APROVACAO', 'Aguardando Cliente'), ('PRODUCAO', 'Em Produção (Estamparia)'), ('FINALIZADO', 'Pronto para Entrega'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
