# Generated by Django 6.0 on 2025-12-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por m²')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Em metros (Ex: 1.00)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Em metros (Ex: 0.50)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Arte'), ('ARTE_PRODUCAO', 'Arte em Produção'), ('APROVACAO', 'Aguardando Cliente'), ('PRODUCAO', 'Em Produção'), ('FINALIZADO', 'Pronto para Entrega'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordens.material', verbose_name='Material'),
        ),
    ]
