# Generated by Django 6.0 on 2025-12-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_material_remove_ordemservico_servico_and_more'),
        ('usuarios', '0005_produto_statusos_alter_setor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.produto', verbose_name='Material/Produto'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
