# Generated by Django 6.0 on 2025-12-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='GestãoPro', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracao/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='configuracao/')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
