# Generated by Django 6.0 on 2025-12-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_configuracaosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pode_ver_financeiro', models.BooleanField(default=False)),
                ('pode_ver_clientes', models.BooleanField(default=True)),
                ('pode_ver_ordens', models.BooleanField(default=True)),
                ('pode_gerir_equipe', models.BooleanField(default=False)),
            ],
        ),
    ]
