# Generated by Django 6.0 on 2025-12-18 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.setor'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('AUXILIAR', 'Auxiliar'), ('OPERADOR', 'Operador'), ('GERENTE', 'Gerente'), ('DIRETOR', 'Diretor'), ('DONO', 'Proprietário')], default='AUXILIAR', max_length=20),
        ),
    ]
