# Generated by Django 6.0 on 2025-12-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_setor_alter_perfil_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preco_revenda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('aberto', 'Aberto / Na Fila'), ('em_producao', 'Em Produção'), ('finalizado', 'Finalizado / Pronto'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('cor', models.CharField(default='#6c757d', max_length=7)),
            ],
            options={
                'verbose_name': 'Status de OS',
                'verbose_name_plural': 'Status de OS',
            },
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='nome_empresa',
            field=models.CharField(default='GestãoPro', max_length=100),
        ),
    ]
